"""empty message

Revision ID: 11e220bde0ce
Revises: be5a890357c9
Create Date: 2019-08-01 16:55:36.328015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e220bde0ce'
down_revision = 'be5a890357c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productcategoties', sa.Column('product_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productcategoties', 'products', ['product_category_id'], ['id'])
    op.drop_constraint('products_product_category_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'product_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_product_category_id_fkey', 'products', 'productcategoties', ['product_category_id'], ['id'])
    op.drop_constraint(None, 'productcategoties', type_='foreignkey')
    op.drop_column('productcategoties', 'product_category_id')
    # ### end Alembic commands ###
