"""empty message

Revision ID: 4242ce595fe5
Revises: 11e220bde0ce
Create Date: 2019-08-01 16:56:53.175616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4242ce595fe5'
down_revision = '11e220bde0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productcategoties_product_category_id_fkey', 'productcategoties', type_='foreignkey')
    op.drop_column('productcategoties', 'product_category_id')
    op.add_column('products', sa.Column('product_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'productcategoties', ['product_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_category_id')
    op.add_column('productcategoties', sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('productcategoties_product_category_id_fkey', 'productcategoties', 'products', ['product_category_id'], ['id'])
    # ### end Alembic commands ###
