"""empty message

Revision ID: 6f681f581bc4
Revises: ff61ea8b8616
Create Date: 2019-08-01 16:34:18.181904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f681f581bc4'
down_revision = 'ff61ea8b8616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.add_column('productcategoties', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productcategoties', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productcategoties', type_='foreignkey')
    op.drop_column('productcategoties', 'product_id')
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='image_pkey')
    )
    # ### end Alembic commands ###
