"""empty message

Revision ID: 83385407d7de
Revises: c676b765df2e
Create Date: 2019-07-14 18:27:30.848946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83385407d7de'
down_revision = 'c676b765df2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
