"""empty message

Revision ID: 8a68e7b02c7b
Revises: e73f6080d266
Create Date: 2019-07-18 15:23:50.217227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a68e7b02c7b'
down_revision = 'e73f6080d266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price2')
    # ### end Alembic commands ###
