"""empty message

Revision ID: 90f35a14820a
Revises: 83385407d7de
Create Date: 2019-07-15 20:02:15.658564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f35a14820a'
down_revision = '83385407d7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('parameter', sa.String(length=100), nullable=True))
    op.drop_constraint('contacts_title_key', 'contacts', type_='unique')
    op.create_unique_constraint(None, 'contacts', ['parameter'])
    op.drop_column('contacts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contacts', type_='unique')
    op.create_unique_constraint('contacts_title_key', 'contacts', ['title'])
    op.drop_column('contacts', 'parameter')
    # ### end Alembic commands ###
