"""empty message

Revision ID: be5a890357c9
Revises: 6f681f581bc4
Create Date: 2019-08-01 16:47:21.631552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5a890357c9'
down_revision = '6f681f581bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productcategoties_product_id_fkey', 'productcategoties', type_='foreignkey')
    op.drop_column('productcategoties', 'product_id')
    op.add_column('products', sa.Column('product_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'productcategoties', ['product_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_category_id')
    op.add_column('productcategoties', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('productcategoties_product_id_fkey', 'productcategoties', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
