"""empty message

Revision ID: ff61ea8b8616
Revises: ffa2b2d7297c
Create Date: 2019-07-18 16:17:27.231528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff61ea8b8616'
down_revision = 'ffa2b2d7297c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img', sa.Unicode(length=128), nullable=True))
    op.drop_column('products', 'price2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'img')
    # ### end Alembic commands ###
